export enum NotificationType {
  TASK_REMINDER = 'TASK_REMINDER',
  TASK_OVERDUE = 'TASK_OVERDUE',
  TASK_COMPLETED = 'TASK_COMPLETED',
  MOTIVATIONAL = 'MOTIVATIONAL',
  VERIFY_EMAIL = 'VERIFY_EMAIL',
  PASSWORD_RESET = 'PASSWORD_RESET'
}
