export enum PointTransactionType {
  TASK_COMPLETED = 'TASK_COMPLETED',
  POMODORO_COMPLETED = 'POMODORO_COMPLETED',
  STORE_REDEMPTION = 'STORE_REDEMPTION',
  ADMIN_ADJUSTMENT = 'ADMIN_ADJUSTMENT',
}
